---
- name: Recursively remove directory if it exists
  ansible.builtin.file:
    path: "{{ frontend_docker_dir }}"
    state: absent
  when: inventory_hostname == groups['DockerSwarmManager'][0] or inventory_hostname in groups['App']

- name: Create frontend directory
  become: yes
  ansible.builtin.file:
    path: "{{ frontend_docker_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory
  when: inventory_hostname == groups['DockerSwarmManager'][0] or inventory_hostname in groups['App']

- name: Copy frontend source folder with owner and permissions
  # ansible.builtin.copy:
  #   src: ../../Project-frontend/
  #   dest: "{{ frontend_docker_dir }}/"
  #   owner: "{{ ansible_user }}"
  #   group: "{{ ansible_user }}"
  #   mode: '0644'
  synchronize:
    src: ../../Project-frontend/
    dest: "{{ frontend_docker_dir }}/"
    mode: push
    delete: true
    rsync_opts:
      - "--exclude=.next/"
      - "--exclude=node_modules/"
      - "--exclude=next-env.d.ts"
  when: inventory_hostname == groups['DockerSwarmManager'][0] or inventory_hostname in groups['App']

- name: Copy docker-compose file with owner and permissions
  become: yes
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ frontend_docker_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  when: inventory_hostname == groups['DockerSwarmManager'][0]


- name: Install pip library
  become: yes
  ansible.builtin.pip:
    name: ["jsondiff"]
    state: latest
  when: inventory_hostname == groups['DockerSwarmManager'][0]

- name: Build an image
  become: yes
  community.docker.docker_image:
    build:
      path: "{{ frontend_docker_dir }}"
    name: frontend
    source: build
  when: inventory_hostname == groups['DockerSwarmManager'][0] or inventory_hostname in groups['App']

- name: Run docker stack to deploy frontend
  become: yes
  community.docker.docker_stack:
    compose: "{{ frontend_docker_dir }}/docker-compose.yaml"
    name: "frontend"
  when: inventory_hostname == groups['DockerSwarmManager'][0]
