---
# Create an instance on NeCTAR
- name: Create an instance
  openstack.cloud.server:
    name: "{{ item.name }}"
    auto_floating_ip: false
    availability_zone: "{{ availability_zone }}"
    flavor: "{{ instance_flavor }}"
    image: "{{ instance_image }}"
    key_name: "{{ instance_key_name }}"
    network: "{{ instance_network }}"
    security_groups: "{{ sg_names }}"
    timeout: 600
    volumes: "{{ item.volumes }}"
    state: present
    wait: true
  loop: "{{ instances }}"
  register: os_instance

- ansible.builtin.debug:
    msg: "Instance {{ item.server.name }} has been created. IP address is {{ item.server.addresses['qh2-uom-internal'][0].addr }}"
  loop: "{{ os_instance.results }}"
  when: item.server is defined

# - name: Print content of ssh private key
#   ansible.builtin.shell: cat {{ ansible_ssh_private_key_file }}
#   register: private_key_content

# - name: Debug private key content
#   ansible.builtin.debug:
#     var: private_key_content.stdout
    
- name: Wait for connection
  ansible.builtin.wait_for:
    msg: "Instance {{ item.server.name }} has been created. IP address is {{ item.server.addresses['qh2-uom-internal'][0].addr }}"
    host: "{{ item.server.addresses['qh2-uom-internal'][0].addr }}"
    port: 22
    timeout: 120
    search_regex: OpenSSH
  loop: "{{ os_instance.results }}"
  when: item.server is defined


# Add hosts to Ansible in-memory inventory
- name: Add host
  ansible.builtin.add_host:
    name: "{{ item.server.addresses['qh2-uom-internal'][0].addr }}"
    groups: localhost
  loop: "{{ os_instance.results }}"
  when: item.server is defined
