- hosts: AllInstances
  gather_facts: false

  vars_files:
    - host_vars/mastodon.yaml

  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: ~/.ssh/mrc_cloud.key
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    - ansible_python_interpreter: /usr/bin/python3

    - couchdb_endpoint: http://admin:comp90024-60@172.26.136.78:5984/
    - couchdb_database: mastodon
    
  roles:
    - role: harvester