- hosts: AllInstances
  gather_facts: true

  vars_files:
    - host_vars/volumes.yaml

  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: ~/.ssh/mrc_cloud.key
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  roles:
    - role: volumes
    - role: common
    - role: docker
    - role: docker-swarm